version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: evolvedm/openvpn-rpi
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - /PATCH_CONFIG_OPENVPN/:/etc/openvpn
